export interface XtalFigParallelogramProps extends HTMLElement{
    topLeft: number, 
    topRight: number, 
    bottomRight: number, 
    width: number, 
    strokeWidth:number, 
    height:number, 
    slant:number,
    heightMinusStroke:number,
    innerX:number,
    innerY:number,
    innerWidth:number,
    innerHeight:number,
    fillPath:string,
    borderPath:string,
    self: XtalFigParallelogramProps,
}